readme.org

Fix a phrase that seemed gramatically lapsed.

readme.org: fix phrasing around os.write returns

---

src/Entity/WeakTerm/ToText.hs

(And say goodbye to the vestige of the old S-Expression syntax)

Reimplement `Entity.WeakTerm.ToText` for the new syntax

---

book/src/other-built-in-utilities.md
book/theme/book.js
src/Scene/Parse/RawTerm.hs
test/term/with/module.ens
test/term/with/source/with.nt

This PR adds the following notation:
```
// base case
with binder {
e
}
↓
e
// step case (for let)
with binder {
let x = e in
cont
}
↓
let x = e in
with binder { cont }
// step case (for seq)
with binder {
e;
cont
}
↓
e;
with binder { cont }
// step case (for bind)
with binder {
bind x = e in
cont
}
↓
binder(with binder { e }, (x) => {
with binder { cont }
})
```
Example:
```neut
// binder (the bind operator of the except monad)
define except-bind[e, a, b](x: except(e, a), k: a -> except(e, b)): except(e, b) {
match x {
- Fail(err) => Fail(err)
- Pass(value) => k(value)
}
}
// try the `with` notation
define test(): except(&text, int) {
with except-bind {
bind _: bool = Fail("hello") in
let _ = tau in
bind _: bool =
bind _: bool = Pass(True) in // with-notation is nestable
Fail("hello")
in …
```

Add a notation for (not necessarily) monadic bind

---

src/Scene/Parse/Discern.hs

Before:
```
// reports nothing
let x = tau in
Unit
```
After:
```
// reports "defined but not used: `x`"
let x = tau in
Unit
```

Remove the wrong `UnusedVariable.delete`

---

src/Main.hs
src/Scene/Parse/Discern.hs
src/Scene/Parse/RawTerm.hs

This PR:
1. fixes `hPutChar: invalid argument (cannot encode character '..')` by specifying utf-8 explicitly.
2. fixes broken location info by preventing cached locations being overwritten by temporary variables.

LSP-related fixes

---

src/Scene/Parse/Discern.hs
src/Scene/Parse/Discern/Name.hs
src/Scene/Parse/RawTerm.hs
test/term/var/source/var.nt

Before this PR:
```
let Foo = e in // ← the `Foo` is regarded as a variable
cont
```
After this PR:
```
let Foo = e in // ← the `Foo` is regarded as a nullary constructor
cont
```
The latter is thus equivalent to:
```
match e {
- Foo => cont
}
```

Fix the handling of nullary constructors in `let`s

---

src/Context/Definition.hs
src/Context/WeakDefinition.hs
src/Entity/Const.hs
src/Entity/Module.hs
src/Entity/Stmt.hs
src/Entity/Term.hs
src/Entity/Term/Weaken.hs
src/Scene/Clarify.hs
src/Scene/Elaborate.hs
src/Scene/Elaborate/Infer.hs
src/Scene/Elaborate/Reveal.hs
src/Scene/Initialize.hs
src/Scene/LSP/Lint.hs
src/Scene/Module/Reflect.hs
src/Scene/New.hs
src/Scene/Parse.hs
src/Scene/Parse/Discern.hs
src/Scene/Parse/RawTerm.hs
src/Scene/Term/Inline.hs
test/pfds/binomial-heap/source/binomial-heap.nt
test/statement/variant-struct/source/variant-struct.nt

Added:
```
// the body of a constant (`e` in this case) must be reduced into a value at compile-time
constant foo: some-type {
e
}
```
Removed:
```
// this can be replaced with: `constant foo: tau { e }`
type foo {
e
}
// this can be replaced with: `inline foo(x: A) { e }`
type foo(x: A) {
e
}
```

Add a statement `constant` (and remove `type`)

---

src/Act/LSP.hs
src/Scene/LSP.hs

This PR fixes the LSP server so that it reflects changes to `module.ens` immediately.

Fix: don't reuse the app env when running the LSP server

---

src/Act/Build.hs
src/Context/Cache.hs
src/Context/Gensym.hs
src/Entity/Cache.hs
src/Entity/DefiniteDescription.hs
src/Entity/Hint.hs
src/Entity/PrimOp/FromText.hs
src/Entity/PrimType/FromText.hs
src/Entity/Stmt.hs
src/Entity/Term.hs
src/Entity/Term/Compress.hs
src/Entity/Term/Extend.hs
src/Entity/WeakTerm/ToText.hs
src/Scene/Check.hs
src/Scene/Ens/Reflect.hs
src/Scene/LSP/Complete.hs
src/Scene/Load.hs
src/Scene/Parse.hs
src/Scene/Parse/Core.hs
src/Scene/Unravel.hs

For better compilation speed, this PR:
- parallelizes the build process to some extent,
- drops location information when saving cache, and
- optimizes the internal representation of definite descriptions.
---
```
before:
❯ hyperfine "neut build"
Benchmark 1: neut build
Time (mean ± σ):      1.323 s ±  0.023 s    [User: 1.932 s, System: 0.313 s]
Range (min … max):    1.277 s …  1.351 s    10 runs
after:
❯ hyperfine "neut build"
Benchmark 1: neut build
Time (mean ± σ):      83.1 ms ±   3.9 ms    [User: 125.5 ms, System: 26.5 ms]
Range (min … max):    76.6 ms …  94.7 ms    36 runs
```

Faster compilation when using cache

---

src/Scene/Parse/RawTerm.hs
test/term/pi/source/pi-term.nt

Before:
```
(x: tau) => {x} // allowed
(x: tau) => x // not allowed
(x: tau) => some-func(x) // not allowed
(x: tau) => (y: tau) => foo(x, y) // not alllowed
```
After:
```
(x: tau) => {x} // allowed
(x: tau) => x // allowed
(x: tau) => some-func(x) // allowed
(x: tau) => (y: tau) => foo(x, y) // alllowed
```

Generalize the syntax of pi-intro

---

src/Entity/LocalLocator.hs
src/Entity/RawProgram.hs
src/Entity/RawProgram/Decode.hs
src/Entity/Syntax/Series.hs
src/Scene/Parse/Discern.hs

```
import {
- Foo
- this.unit {Unit, unit}
- this.bool {True}
- Bar
- this.bool {bool, buz}
- this.bool
}
↓ (format)
import {
- Bar
- Foo
- this.bool {True, bool, buz}
- this.unit {Unit, unit}
}
```

Reorganize import-items automatically

---

src/Context/App/Internal.hs
src/Context/Cache.hs
src/Context/Elaborate.hs
src/Context/Global.hs
src/Context/Locator.hs
src/Context/Tag.hs
src/Entity/GlobalName.hs
src/Entity/LocationTree.hs
src/Entity/WeakTerm/ToText.hs
src/Scene/Elaborate.hs
src/Scene/Elaborate/Infer.hs
src/Scene/LSP.hs
src/Scene/LSP/FindDefinition.hs
src/Scene/LSP/GetSymbolInfo.hs
src/Scene/LSP/Highlight.hs
src/Scene/LSP/Lint.hs
src/Scene/LSP/References.hs
src/Scene/Parse/Discern.hs
src/Scene/Parse/Discern/Name.hs
src/Scene/Parse/Discern/Noema.hs

This PR adds support for `textDocument/hover`, which allows LSP clients to show type info of symbols in their lovely popups:
↓ (`lsp-ui-doc-glance` in lsp-mode)

Support `textDocument/hover`

---

src/Act/Build.hs
src/Act/Zen.hs
src/Context/Locator.hs
src/Context/OptParse.hs
src/Context/Path.hs
src/Entity/BaseName.hs
src/Entity/Command.hs
src/Entity/Config/Zen.hs
src/Entity/Const.hs
src/Entity/DefiniteDescription.hs
src/Entity/Module.hs
src/Entity/Source.hs
src/Entity/Target.hs
src/Main.hs
src/Scene/Elaborate.hs
src/Scene/Elaborate/Infer.hs
src/Scene/Install.hs
src/Scene/Module/Reflect.hs
src/Scene/New.hs
src/Scene/Unravel.hs
test/misc/multi-targets/source/main.nt
test/misc/multi-targets/source/multi-targets.nt

This PR adds a subcommand `zen`, a calming way to think about program.
`neut zen FILE` compiles & executes `FILE` as if the function `zen` in the file were `main`.  For example, given the following `foo.nt`:
```
define foo(): text { 
"foo" 
}
define zen(): unit {
print(foo())
}
```
executing `neut zen path/to/foo.nt` results in `"foo"`.
This `zen` can be used against every file in a module, even if the file isn't a main file.

Add `neut zen`

---

src/Context/Cache.hs
src/Context/Path.hs
src/Entity/Cache.hs
src/Scene/Elaborate.hs
src/Scene/LSP/Complete.hs
src/Scene/LSP/GetAllCachesInModule.hs

This PR extracts completion-related parts from cache files. This results in about 5x faster completion.
Run `Scene.LSP.Complete.complete` at `(*)` in the following file:
```
define make-adder(x: int): (int) -> int {
let adder =
(y) => {
add-int(x, y)
}
in
adder
}
define main(): unit {
print-int(make-adder(3)(7)); 
// (*)
print("\n")
}
```
```
total time  =        0.06 secs   (88 ticks @ 1000 us, 10 processors)
total alloc =  79,720,928 bytes  (excludes profiling overheads)
COST CENTRE             MODULE                     SRC                                         %time %alloc
get                     Entity.Hint                src/Entity/Hint.hs:(47,3)-(48,48)            68.2   43.7
get                     Entity.Term                src/Entity/Term.hs:44:10-39                  11.4 …
```

Faster completion by splitting cache files

---

src/Entity/RawTerm.hs
src/Entity/RawTerm/Decode.hs
src/Scene/Parse/Discern.hs
src/Scene/Parse/RawTerm.hs
test/misc/codata-basic/source/codata-basic.nt

Example usage:
```
constant intdict: Dict.trope(int) {
Dict.from-loset(this.int.as-loset)
}
define make-big-dict(): dict(int, int) {
loop(700000, Dict.empty(), (acc, _) => {
let key = random(1000000) in
let val = random(1000000) in
intdict::insert(key, val, acc) // ← here
})
}
```

add a notation: `foo::bar` => `use foo {bar} in bar`

---

src/Act/Zen.hs
src/Context/OptParse.hs
src/Entity/ClangOption.hs
src/Entity/Config/Zen.hs
src/Entity/Module.hs
src/Entity/Target.hs
src/Entity/ZenConfig.hs
src/Scene/Build.hs
src/Scene/Module/Reflect.hs
src/Scene/New.hs

Example:
```ens
{
// ...
zen {
build-option [
"$(pkg-config libpq --libs --cflags)",
],
},
// ...
}
```

pass clang options to `neut zen` via `module.ens`

---

src/Act/Archive.hs
src/Context/OptParse.hs
src/Entity/Config/Archive.hs
src/Entity/DefiniteDescription.hs
src/Entity/List.hs
src/Entity/PackageVersion.hs
src/Scene/PackageVersion/ChooseNewVersion.hs

Example:
```sh
❯ ls archive
0-1-0.tar.zst  0-1-1.tar.zst
❯ neut archive
Note: Selected a new version: 0-1-2
❯ ls archive
0-1-0.tar.zst  0-1-1.tar.zst  0-1-2.tar.zst
```

select an appropriate next version if one isn't specified

---

src/Act/Create.hs
src/Context/OptParse.hs
src/Entity/Config/Create.hs
src/Scene/New.hs

Use `--target` to specify the name of the created target:
```sh
neut create foo --target whatever
cd foo
tree
cat module.ens
```

allow creating modules using specified target names

---

src/Entity/DecisionTree.hs
src/Scene/Elaborate.hs

```neut
data sample {
| Foo
| Bar(int, int)
| Qux
| Buz(tau)
}
define foo(p: pair(list(int), sample)): unit {
match p {
| Pair(Cons(_, _), Foo) =>
Unit
| Pair(Nil, Bar(_, _)) =>
Unit
}
}
```
↓
(before)
```
/path/to/file.nt:9:3
Error: Encountered a non-exhaustive pattern matching
```
(after)
```
/path/to/file.nt:9:3
Error: This pattern matching does not cover:
- Pair(Cons(_, _), Bar(_, _))
- Pair(Cons(_, _), Buz(_))
- Pair(Cons(_, _), Qux)
```

report uncovered patterns

---

src/Entity/RawTerm.hs
src/Entity/RawTerm/Decode.hs
src/Scene/Parse/Discern.hs
src/Scene/Parse/RawTerm.hs

Syntax:
```
pin x = e1 in
e2
```
Semantics:
```neut
pin x = e1 in
e2
↓
let x = e1 in
let result on x = e2 in
let _ = x in
result
```
Example:
```neut
// before
define foo(): unit {
let xs = make-list(123) in
let result on xs = some-func(xs) in
let _ = xs in
result
}
↓
// after
define foo(): unit {
pin xs = make-list(123) in
some-func(xs)
}
```

new syntax: `pin x = e1 in e2`

---

book/src/terms.md
src/Entity/RawTerm/Decode.hs
src/Scene/Parse/Discern.hs
src/Scene/Parse/Discern/Text.hs
test/term/prim/source/prim.nt

The available escape sequences:
| Escape Sequence | Meaning                        |
| --------------- | ------------------------------ |
| `\0`            | U+0000 (null character)        |
| `\t`            | U+0009 (horizontal tab)        |
| `\n`            | U+000A (line feed)             |
| `\r`            | U+000D (carriage return)       |
| `\"`            | U+0022 (double quotation mark) |
| `\\`            | U+005C (backslash)             |
| `` \` ``        | U+0060 (backtick)              |
| `\u{n}`         | U+n                            |

don't leave escape sequences to haskell

---

src/Entity/RawTerm.hs
src/Scene/Parse/Discern.hs
src/Scene/Parse/RawTerm.hs

```neut
catch x = e1 in
e2
↓
match e1 {
| Right(v) =>
Right(v)
| Left(x) =>
e2
}
```

`catch x = e1 in e2`

---

src/Context/Tag.hs
src/Entity/LocationTree.hs
src/Scene/LSP/FindDefinition.hs
src/Scene/LSP/GetSymbolInfo.hs
src/Scene/Parse/Discern/Name.hs

before:
```neut
define my-func(): type {
^^^^^^^^^^^^^^^^^^^^^ (highlighted)
type
}
define main(): unit {
let _ = this.loc-{*}test.my-func in // {*}: cursor
print("Hello, world!\n")
}
```
after:
```neut
define my-func(): type {
^^^^^^^ (highlighted)
type
}
define main(): unit {
let _ = this.loc-{*}test.my-func in // {*}: cursor
print("Hello, world!\n")
}
```

fix: symbol highlighting

---

build/package.template.yaml
src/Act/Format.hs
src/Context/OptParse.hs
src/Entity/AppLsp.hs
src/Entity/CodeAction.hs
src/Entity/Config/Format.hs
src/Scene/Format.hs
src/Scene/LSP.hs
src/Scene/LSP/Format.hs
src/Scene/LSP/Util.hs

- `neut format-source` tracks all the imported files recursively and remove unused items in `import {..}` automatically
- `textDocument/formatting` == (format + remove used items in `import {..}`)
- `neut format-source` simply formats given files
- `neut format-source --minimize-imports` formats given files and removes unused items in `import {..}`
- `textDocument/formatting` == (format)
- Added a new code action for (format + remove used items in `import {..}`)
```sh
❯ hyperfine "neut format-source source/neural.nt"
Benchmark 1: neut format-source source/neural.nt
Time (mean ± σ):      33.6 ms ±   1.3 ms    [User: 14.9 ms, System: 15.8 ms]
Range (min … max):    30.4 ms …  36.1 ms    82 runs
❯ hyperfine "neut format-source --minimize-imports source/neural.nt"
Benchmark 1: neut …
```

remove unused items in `import {..}` only when required (for better LSP experience)

---

src/Act/Check.hs
src/Context/OptParse.hs
src/Entity/AppLsp.hs
src/Entity/CodeAction.hs
src/Entity/Config/Check.hs
src/Scene/Check.hs
src/Scene/Fetch.hs
src/Scene/LSP.hs
src/Scene/LSP/Complete.hs

- added a option: `neut check --full`
- this checks all the dependencies and the main module to generate completion caches
- added a code action that performs `neut check --full`
- performance fix: cache the clang digest in textDocument/completion 
- see below
```sh
❯ hyperfine "neut bench-completion"
Benchmark 1: neut bench-completion
Time (mean ± σ):     215.8 ms ±   8.9 ms    [User: 725.7 ms, System: 680.6 ms]
Range (min … max):   207.4 ms … 242.3 ms    14 runs
❯ hyperfine "neut bench-completion"
Benchmark 1: neut bench-completion
Time (mean ± σ):      45.7 ms ±   1.4 ms    [User: 26.2 ms, System: 25.0 ms]
Range (min … max):    41.8 ms …  48.9 ms    63 runs
```
The subcommand `bench-completion` is only for this performance comparison (not commited to `main`); The internal of the …

improve completion-related stuff

---

src/Entity/RawTerm.hs
src/Entity/RawTerm/Decode.hs
src/Entity/Term.hs
src/Entity/Term/Chain.hs
src/Entity/Term/Compress.hs
src/Entity/Term/Extend.hs
src/Entity/Term/FreeVars.hs
src/Entity/Term/Weaken.hs
src/Entity/WeakTerm.hs
src/Entity/WeakTerm/Eq.hs
src/Entity/WeakTerm/FreeVars.hs
src/Entity/WeakTerm/Holes.hs
src/Entity/WeakTerm/ToText.hs
src/Scene/Clarify.hs
src/Scene/Elaborate.hs
src/Scene/Elaborate/Infer.hs
src/Scene/Parse/Discern.hs
src/Scene/Term/Refresh.hs
src/Scene/Term/Subst.hs
src/Scene/WeakTerm/Fill.hs
src/Scene/WeakTerm/Subst.hs

This PR replaces `<resource>` with the name of a resource type when printing terms.
---
Consider the following program:
```neut
resource some-type {..}
define make(): some-type {..}
define main(): unit {
let x: binary = make() in
Unit
}
```
The output of `neut check` before the fix is:
```sh
Expected:
<resource>
Found:
some-type
```
The output of `neut check` after the fix is:
```sh
Expected:
binary
Found:
some-type
```

fix: don't suppress the names of resource types when printing terms

---

src/Scene/Parse/Discern.hs

(so that the compiler can report undefined variables in the expected order)

alpha-convert `e` in `e(e1, ..., en)` before `e1, ..., en`

---

src/Act/Format.hs
src/Context/Parse.hs
src/Scene/Unravel.hs

Before:
```sh
❯ neut format-source source/foobarbuz.nt
Error: /path/to/source/foobarbuz.nt: withBinaryFile: does not exist (No such file or directory)
```
After:
```sh
❯ neut format-source source/foobarbuz.nt
Error: No such file exists: /path/to/source/foobarbuz.nt
```

fix: ensure file existence before running the formatter

---

src/Scene/LSP/GetLocationTree.hs

The following are benchmarks of a command that executes `textDocument/documentHighlight` five times:
```
// Before this PR
Benchmark 1: neut foo
Time (mean ± σ):     480.3 ms ±   6.0 ms    [User: 390.0 ms, System: 196.8 ms]
Range (min … max):   471.9 ms … 489.5 ms    10 runs
↓
// After this PR
Benchmark 1: neut foo
Time (mean ± σ):      47.5 ms ±   1.5 ms    [User: 17.1 ms, System: 18.9 ms]
Range (min … max):    44.2 ms …  50.8 ms    57 runs
```

remove an unnecessary operation in `getLocationTree` for better LSP performance

---

src/Context/Global.hs

Before:
```neut
data hey {
| Bar
}
data yo {
^^ `Bar` is already defined
| Bar
}
```
After:
```neut
data hey {
| Bar
}
data yo {
| Bar
^^^ `Bar` is already defined
}
```

fix error locations for non-fresh constructors

---

src/Context/External.hs

The command to get the version information of Clang is `clang --version`, not `clang -v`.
Hopefully addresses #268.

Fix: `clang -v` => `clang --version`

---

book/src/primitives.md

previosly primitives.html referenced a type `data void {}` in neut core. 
This definition doesn't seem to exist in core.
However `data null {}` exists.

fix book reference to `null` type in core

---

book/src/modality-and-memory.md
src/Scene/Parse/Discern.hs

```neut
define yo(): meta unit {
let x = box {Unit} in
letbox v =
let f =
function () { // (*)
box {x}
}
in
f()
in
v
}
```
```
Error at (*): "This closure is at layer 1, but the free variable `x` is at the layer 0 (≠ 1)"
```
```
(No error)
```

relax unnecessarily strict constraints on free variables

---

book/src/how-to-execute-types.md

Context:
- #290
(I previously reordered these arguments to match LLVM's [`store`](https://llvm.org/docs/LangRef.html#store-instruction), and it looks like some typos slipped in during that process)

fix typos in `how-to-execute-types`

---

src/Kernel/Elaborate/Move/Elaborate.hs
src/Kernel/Elaborate/Move/Internal/Handle/Elaborate.hs
src/Kernel/Parse/Move/Interpret.hs

```sh
❯ hyperfine "neut clean && neut build test"
Benchmark 1: neut clean && neut build test
Time (mean ± σ):     598.6 ms ±   9.2 ms    [User: 1427.3 ms, System: 560.8 ms]
Range (min … max):   585.9 ms … 614.1 ms    10 runs
❯ hyperfine "neut clean && neut build test"
Benchmark 1: neut clean && neut build test
Time (mean ± σ):     588.3 ms ±   6.8 ms    [User: 1405.3 ms, System: 548.2 ms]
Range (min … max):   580.5 ms … 598.6 ms    10 runs
```

save completion caches in Parse.Move.Interpret

---

src/Kernel/Elaborate/Move/Elaborate.hs
src/Kernel/Elaborate/Move/Internal/Infer.hs
src/Kernel/Elaborate/Move/Internal/WeakTerm/Fill.hs
src/Kernel/Elaborate/Rule/Stuck.hs
src/Kernel/Parse/Move/Internal/Discern.hs
src/Kernel/Parse/Move/Internal/Discern/Name.hs
src/Kernel/Parse/Move/Internal/RawTerm.hs
src/Language/RawTerm/Rule/RawTerm.hs
src/Language/RawTerm/Rule/RawTerm/ToDoc.hs
src/Language/Term/Rule/Term/Weaken.hs
src/Language/WeakTerm/Move/Reduce.hs
src/Language/WeakTerm/Move/Subst.hs
src/Language/WeakTerm/Rule/WeakTerm.hs
src/Language/WeakTerm/Rule/WeakTerm/Eq.hs
src/Language/WeakTerm/Rule/WeakTerm/FreeVars.hs
src/Language/WeakTerm/Rule/WeakTerm/Holes.hs
src/Language/WeakTerm/Rule/WeakTerm/ToText.hs

example:
```
define id<a>(x: a): a {
x
}
define use-id(): unit {
let x = id(Unit);
let x = id<unit>(Unit);          // new
let x = id<unit> of {x := Unit}; // new
Unit
}
```

allow specifying implicit arguments explicitly

---

src/Kernel/Common/Move/Handle/Global/KeyArg.hs
src/Kernel/Common/Rule/Handle/Global/KeyArg.hs
src/Kernel/Parse/Move/Internal/Discern.hs
src/Kernel/Parse/Move/Internal/RawTerm.hs
src/Kernel/Parse/Move/Parse.hs
src/Language/RawTerm/Rule/RawTerm.hs
src/Language/RawTerm/Rule/RawTerm/ToDoc.hs

before:
```
define id<a>(x: a): a {
x
}
define use-id(): unit {
let x = id<unit> of {x := Unit};
Unit
}
```
after:
```
define id<a>(x: a): a {
x
}
define use-id(): unit {
let x = id of {a := unit, x := Unit};
Unit
}
```

specify implicit arguments in `of`

---

src/CodeParser/Move/Parse.hs
src/Ens/Rule/Ens/ToDoc.hs
src/Language/RawTerm/Rule/RawStmt/ToDoc.hs
src/Language/RawTerm/Rule/RawTerm/ToDoc.hs
src/PrettyPrinter/Rule/Doc.hs
src/SyntaxTree/Rule/C.hs
src/SyntaxTree/Rule/C/ToDoc.hs

before:
```
define yo(): unit {
print("Yo") // Yo
}
↓ (format)
define yo(): unit {
print("Yo")
// Yo
}
```
after:
```
define yo(): unit {
print("Yo") // Yo
}
↓ (format)
define yo(): unit {
print("Yo") // Yo
}
```

add support for formatting inline comments

---

book/src/modality-and-memory.md

Attempt at making the example on that use-after-free in the docs more clear and provide an example on the usage of `meta`.
The provided example is made from the perspective of someone who didn't know how this worked some time ago so it may be helpful for those who aren't yet familiarized with the concept.
I believe it to be more informal than the rest of the docs, I am willing to try rewrite this piece of thing.
The only (I hope at least) promises I can't make are time related ones!

update docs with an example for meta

---

src/Kernel/Common/CreateGlobalHandle.hs
src/Kernel/Parse/Internal/Import.hs
src/Kernel/Unravel/Unravel.hs

before:
```
❯ hyperfine "neut check"
Benchmark 1: neut check
Time (mean ± σ):     626.0 ms ±  18.9 ms    [User: 1014.3 ms, System: 294.5 ms]
Range (min … max):   601.3 ms … 658.2 ms    10 runs
```
after:
```
❯ hyperfine "neut check"
Benchmark 1: neut check
Time (mean ± σ):     355.9 ms ±   9.4 ms    [User: 793.5 ms, System: 184.7 ms]
Range (min … max):   343.4 ms … 369.6 ms    10 runs
```
(`$PWD == (repo-root)/neut/`)

cache preset info
