src/Clarify.hs, src/Data/Env.hs, src/Data/Log.hs, src/Data/Platform.hs, src/Data/Syscall.hs, src/Emit.hs
I am a beginner to Haskell, so please do tell me if my code is unidiomatic. In particular, is there any better way to handle unimplemented paths than `error "unimplemented"`?
=> Implement basic support for AArch64

.github/workflows/linux.yaml
This PR fixes paths in `.github/workflows/linux.yaml`. I forgot to update them when parameterizing the version of the compiler.
=> Fix paths in the workflow (for better cache behavior)

src/Scene/Clarify.hs, src/Scene/Clarify/Sigma.hs
Just treat them as immediates.
=> Resource types for enums are unnecessary

src/Act/Build.hs, src/Context/DataDefinition.hs, src/Context/Global.hs, src/Context/Locator.hs, src/Context/Tag.hs, src/Entity/BaseName.hs, src/Entity/Hint.hs, src/Entity/Ident.hs, src/Entity/LocalLocator.hs, src/Entity/LocationTree.hs, src/Entity/Stmt.hs, src/Entity/StmtKind.hs, src/Entity/Term/Weaken.hs, src/Scene/Clarify.hs, src/Scene/Elaborate.hs, src/Scene/LSP.hs, src/Scene/LSP/FindDefinition.hs, src/Scene/LSP/FindReferences.hs, src/Scene/LSP/GetLocationTree.hs, src/Scene/LSP/Lint.hs, src/Scene/Parse.hs, src/Scene/Parse/Discern.hs, src/Scene/Parse/Discern/Name.hs, src/Scene/Parse/Discern/Noema.hs, src/Scene/Parse/Discern/PatternMatrix.hs, src/Scene/Parse/Import.hs
- New: support `textDocument/documentHighlight`
- New: jump to definitions from import lists
- Fix: location-related bugs
=> LSP-related improvements/fixes

src/Context/Tag.hs, src/Entity/LocationTree.hs, src/Scene/LSP.hs, src/Scene/LSP/FindReferences.hs, src/Scene/Parse.hs, src/Scene/Parse/Discern/Name.hs, src/Scene/Parse/Discern/Struct.hs, src/Scene/Parse/Import.hs
- Fix: don't overwrite locations of conses by those of holes
- Fix: don't treat file locators as references
- Fix: don't highlight def locations of other files in current file
=> Further fixes of the LSP server

src/Scene/Parse/RawTerm.hs
```
idealize x1, ..., xn {
e
}
↓ desuger
let result on x1, ..., xn = e in
let _ = x1 in
...
let _ = xn in
result
```
=> add `idealize x1, ..., xn { ... }`

src/Act/Format.hs, src/Entity/AppLsp.hs, src/Scene/Ens/Reflect.hs, src/Scene/Format.hs, src/Scene/LSP.hs, src/Scene/LSP/Format.hs
Thanks to [VFS](https://hackage.haskell.org/package/lsp-2.3.0.0/docs/Language-LSP-VFS.html).
=> Support `textDocument/willSaveWaitUntil` (and thus format-on-save)

.gitignore, src/Act/Archive.hs, src/Act/Build.hs, src/Act/Get.hs, src/Act/Zen.hs, src/Context/Module.hs, src/Context/Path.hs, src/Entity/Const.hs, src/Entity/Module.hs, src/Scene/Fetch.hs, src/Scene/Module/Reflect.hs, src/Scene/New.hs, src/Scene/Source/Reflect.hs, src/Scene/Unravel.hs, test/test-darwin.sh, test/test-linux-single.sh, test/test-linux.sh
This PR should feel something like `virtualenvs.in-project: false` → `virtualenvs.in-project: true`
=> make dependencies local to projects

src/Act/Zen.hs, src/Context/Cache.hs, src/Context/LLVM.hs, src/Context/Locator.hs, src/Context/Path.hs, src/Entity/Target.hs, src/Scene/Build.hs, src/Scene/Check.hs, src/Scene/Elaborate.hs, src/Scene/Format.hs, src/Scene/LSP/Complete.hs, src/Scene/LSP/GetAllCachesInModule.hs, src/Scene/LSP/GetLocationTree.hs, src/Scene/LSP/GetSymbolInfo.hs, src/Scene/Link.hs, src/Scene/Load.hs, src/Scene/Parse.hs, src/Scene/Unravel.hs
(to avoid using incorrect cache files)
=> fix: use per-target compilation options when calculating signatures

src/Scene/Parse/Discern.hs
Before:
```neut
// <*>: cursor
define foo(my-var: type): unit {
let _ on my-var =
let _ = my<*>-var in
type
in
Unit
}
↓ (jump-to-definition)
define foo(my-var: type): unit {
let _ on m<*>y-var =
let _ = my-var in
type
in
Unit
}
↓ (jump-to-definition)
define foo(my-var: type): unit {
let _ on m<*>y-var =
let _ = my-var in
type
in
Unit
}
```
After:
```neut
define foo(my-var: type): unit {
let _ on my-var =
let _ = my<*>-var in
type
in
Unit
}
↓ (jump-to-definition)
define foo(my-var: type): unit {
let _ on m<*>y-var =
let _ = my-var in
type
in
Unit
}
↓ (jump-to-definition)
define foo(m<*>y-var: type): unit {
let _ on my-var =
let _ = my-var in
type
in
Unit
}
```
=> fix location info of box-variables

src/Context/External.hs, src/Context/LLVM.hs, src/Entity/ProcessRunner/Context/IO.hs, src/Entity/ProcessRunner/Rule.hs, test/test-linux-single.sh
to avoid weird errors like https://github.com/vekatze/neut/issues/268
=> fix: don't use `throw` in `withCreateProcess`

src/Context/App/Internal.hs, src/Context/Debug.hs, src/Context/External.hs, src/Context/LLVM.hs, src/Context/Module.hs, src/Context/OptParse.hs, src/Context/Path.hs, src/Context/Remark.hs, src/Entity/Config/Remark.hs, src/Scene/Build.hs, src/Scene/Check.hs, src/Scene/Format.hs, src/Scene/Initialize.hs, src/Scene/Link.hs, src/Scene/Load.hs, src/Scene/Unravel.hs
(To make it easier to diagnose situations like #280)
=> add a CLI option: `--enable-debug-output`

book/src/SUMMARY.md, book/src/benchmarks.md, book/src/hello-modules.md, book/src/installation.md, book/src/modality-and-memory.md, book/src/modules-and-sources.md, book/src/modules.md, book/src/overview.md, book/src/primitives.md, book/src/programming-in-neut.md, book/src/static-memory-management.md, book/src/terms.md, book/src/tutorial.md, book/theme/css/general.css, readme.md
- reorganize the tutorial
- avoid uncommon words when possible
- fix other minor stuff
=> improve docs

src/Aux/CodeParser/Rule/Parser.hs, src/Aux/Error/Move/Run.hs, src/Aux/Logger/Move/Log.hs, src/Aux/Logger/Rule/Log.hs, src/Command/Common/Move/Build.hs, src/Command/Common/Move/Check.hs, src/Command/Common/Move/Format.hs, src/Command/LSP/Move/Internal/Util.hs, src/Kernel/Clarify/Move/Clarify.hs, src/Kernel/Clarify/Move/Internal/Sigma.hs, src/Kernel/Common/Move/Handle/Global/Artifact.hs, src/Kernel/Common/Move/Handle/Global/KeyArg.hs, src/Kernel/Common/Move/Handle/Global/Module.hs, src/Kernel/Common/Move/Handle/Global/OptimizableData.hs, src/Kernel/Common/Move/Handle/Local/Locator.hs, src/Kernel/Common/Rule/GlobalName.hs, src/Kernel/Common/Rule/Handle/Local/Locator.hs, src/Kernel/Common/Rule/LocationTree.hs, src/Kernel/Parse/Move/Internal/Discern.hs, src/Kernel/Parse/Move/Internal/Discern/Data.hs, src/Kernel/Parse/Move/Internal/Handle/GlobalNameMap.hs, src/Kernel/Parse/Move/Internal/Handle/NameMap.hs, src/Kernel/Parse/Move/Internal/Handle/Unused.hs, src/Kernel/Parse/Move/Interpret.hs, src/Kernel/Parse/Move/Parse.hs, src/Language/RawTerm/Rule/PostRawStmt.hs, src/Language/RawTerm/Rule/RawStmt.hs, src/Language/RawTerm/Rule/RawTerm.hs, src/Language/RawTerm/Rule/RawTerm/ToDoc.hs
```sh
❯ hyperfine "neut clean && neut build test"
Benchmark 1: neut clean && neut build test
Time (mean ± σ):     750.0 ms ±   8.4 ms    [User: 1485.2 ms, System: 592.3 ms]
Range (min … max):   738.5 ms … 763.4 ms    10 runs
❯ hyperfine "neut clean && neut build test"
Benchmark 1: neut clean && neut build test
Time (mean ± σ):     618.6 ms ±  14.2 ms    [User: 1489.6 ms, System: 571.8 ms]
Range (min … max):   593.4 ms … 641.9 ms    10 runs
```
=> parse in parallel

src/Kernel/Clarify/Move/Clarify.hs, src/Language/Common/Rule/BaseName.hs
(for better profiling experience)
=> embed names of local functions in binaries

book/src/basis.md, book/src/commands.md, book/src/how-to-execute-types.md, book/src/modality-and-memory.md, book/src/modules-and-sources.md, book/src/modules.md, book/src/programming-in-neut.md, book/src/static-memory-management.md, book/src/terms.md, book/src/what-is-next.md
=> docs: wording, grammar, etc.

src/Kernel/Parse/Move/Internal/Discern.hs, src/Kernel/Parse/Move/Internal/RawTerm.hs, src/Language/RawTerm/Rule/RawTerm.hs, src/Language/RawTerm/Rule/RawTerm/ToDoc.hs
example:
```neut
define foo(xs: list(int)): ?unit {
try value on xs = my-func(xs);
Right(value)
}
```
=> allow `try-on`

src/Language/WeakTerm/Rule/WeakTerm/ToText.hs
=> fix `toText`

book/src/programming-in-neut.md, book/src/statements.md, book/src/terms.md
=> fix docs (args, params)

.github/workflows/macos.yaml
=> fix caching stuff

.github/workflows/linux.yaml, .github/workflows/macos.yaml
=> ci: handle the "Pending" state of required checks

src/Kernel/Common/Handle/Global/Module.hs, src/Kernel/Common/Handle/Global/Path.hs
=> Fix file name collisions

src/Command/LSP/Internal/Complete.hs
=> fix(lsp): insert `import {..}` at the beginning of a file

.github/workflows/linux.yaml, .github/workflows/macos.yaml
=> fix: run CI workflows after merging into main

neut/module.ens, neut/source/path/ensure-file-existence.nt, neut/source/path/read.nt, neut/source/path/write.nt
=> port: `src/Path`

neut/source/gensym/gensym.nt
=> port: `src/Gensym`

neut/source/syntax-tree/block.nt, neut/source/syntax-tree/comment.nt, neut/source/syntax-tree/series.nt
=> port: `src/SyntaxTree/{Block,Comment,Series}.hs`

neut/module.ens, neut/source/code-parser/get-info.nt, neut/source/code-parser/parser.nt, neut/source/syntax-tree/comment.nt
=> port: `src/CodeParser/`

neut/module.ens, neut/source/command-parser/command.nt, neut/source/command-parser/config/archive.nt, neut/source/command-parser/config/build.nt, neut/source/command-parser/config/check.nt, neut/source/command-parser/config/clean.nt, neut/source/command-parser/config/create.nt, neut/source/command-parser/config/format-ens.nt, neut/source/command-parser/config/format-source.nt, neut/source/command-parser/config/get.nt, neut/source/command-parser/config/log.nt, neut/source/command-parser/config/version.nt, neut/source/command-parser/config/zen.nt, neut/source/command-parser/parse.nt, neut/source/main.nt, src/Kernel/Parse/Internal/Program.hs
=> port: `src/CommandParser`

neut/source/pretty-printer/doc.nt, neut/source/pretty-printer/piece.nt
=> port: `src/PrettyPrinter/`

neut/source/code-parser/parser.nt, neut/source/syntax-tree/comment.nt, neut/source/syntax-tree/comment/to-doc.nt, neut/source/syntax-tree/series.nt, neut/source/syntax-tree/series/to-doc.nt
=> port: `src/SyntaxTree/{C,Series}/ToDoc.hs`

neut/source/ens/parse.nt, neut/source/ens/to-doc.nt
=> port: `src/Ens/ToDoc.hs`

.env, .github/workflows/macos.yaml, neut/source/language/common/base-name.nt, neut/source/language/common/decision-tree.nt, neut/source/language/common/definite-description.nt, neut/source/language/common/discriminant.nt, neut/source/language/common/geist.nt, neut/source/language/common/global-locator.nt, neut/source/language/common/module-digest.nt, neut/source/language/common/module-id.nt, neut/source/language/common/prim-op/from-text.nt, neut/source/language/common/prim-type/from-text.nt, neut/source/language/common/stmt-kind.nt, neut/source/language/common/strict-global-locator.nt
=> port: `src/Language/Common`

neut/source/language/raw-term/create-hole.nt, neut/source/language/raw-term/necessity-variant.nt, neut/source/language/raw-term/raw-binder.nt, neut/source/language/raw-term/raw-pattern.nt, neut/source/language/raw-term/raw-stmt.nt, neut/source/language/raw-term/raw-stmt/to-doc.nt, neut/source/language/raw-term/raw-term.nt, neut/source/language/raw-term/raw-term/to-doc.nt
=> port: `src/Language/RawTerm/`

src/Command/LSP/Internal/Complete.hs, src/Command/LSP/Internal/Server.hs
=> filter completion items for better LSP performance

neut/module.ens, neut/source/kernel/common/const.nt, neut/source/kernel/common/kit/global/env.nt, neut/source/kernel/common/kit/global/key-arg.nt, neut/source/kernel/common/kit/global/module.nt, neut/source/kernel/common/kit/global/path.nt, neut/source/kernel/common/kit/global/platform.nt, neut/source/kernel/common/kit/global/type.nt, neut/source/kernel/common/module.nt, neut/source/kernel/common/run-process.nt, neut/source/kernel/common/source.nt, neut/source/language/common/definite-description.nt, neut/source/language/weak-term/weak-term.nt, neut/source/logger/hint.nt
=> port: `src/Kernel/Common/` (6/8)

neut/module.ens, neut/source/kernel/common/cache.nt, neut/source/kernel/common/create-local-kit.nt, neut/source/kernel/common/kit/global/artifact.nt, neut/source/kernel/common/kit/global/env.nt, neut/source/kernel/common/kit/global/module.nt, neut/source/kernel/common/kit/global/path.nt, neut/source/kernel/common/kit/local/locator.nt, neut/source/kernel/common/kit/local/tag.nt, neut/source/kernel/common/location-tree.nt, neut/source/kernel/common/manage-cache.nt, neut/source/kernel/common/module/get-enabled-preset.nt, neut/source/kernel/common/module/get-module.nt, neut/source/kernel/common/readable-dd.nt, neut/source/language/common/attr/lam.nt, neut/source/language/common/binder.nt, neut/source/language/common/decision-tree.nt, neut/source/language/common/definite-description.nt, neut/source/language/common/geist.nt, neut/source/language/common/lam-kind.nt, neut/source/language/common/local-locator.nt, neut/source/language/common/stmt-kind.nt, neut/source/language/term/compress.nt, neut/source/language/term/extend.nt, neut/source/language/term/stmt.nt, neut/source/logger/log.nt, neut/source/path/util.nt
=> port: `src/Kernel/Common/` (8/8)
